//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalonWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_Admin
    {
        public int Id { get; set; }
        public string AdminName { get; set; }
        public string AdminPassword { get; set; }
        public string LoginCount { get; set; }
        public DateTime LastTime { get; set; }
        public string Lock { get; set; }
    }
}
