//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalonWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_GoodsCar
    {
        public int Id { get; set; }
        public Nullable<int> GoodsId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> SeqNo { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    
        public virtual BS_Goods BS_Goods { get; set; }
    }
}
