//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalonWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_Goods
    {
        public BS_Goods()
        {
            this.BS_GoodsCar = new HashSet<BS_GoodsCar>();
            this.BS_OrderDetail = new HashSet<BS_OrderDetail>();
        }
    
        public int Id { get; set; }
        public string GoodsName { get; set; }
        public string GoodsType { get; set; }
        public string GoodsPic { get; set; }
        public string GoodsPrice { get; set; }
        public string Detail { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string Blank { get; set; }
    
        public virtual ICollection<BS_GoodsCar> BS_GoodsCar { get; set; }
        public virtual ICollection<BS_OrderDetail> BS_OrderDetail { get; set; }
    }
}
