//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalonWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_Service
    {
        public BS_Service()
        {
            this.BS_Appointment = new HashSet<BS_Appointment>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Price { get; set; }
        public string Detail { get; set; }
        public string ServerPic { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    
        public virtual ICollection<BS_Appointment> BS_Appointment { get; set; }
    }
}
